version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - rm -rf node_modules/ package-lock.json
      - npm config set registry https://registry.npmjs.com/
  build:
    commands:
      - rm -rf node_modules/ package-lock.json
      - npm install
      - npm run build
  post_build:
    commands:
      - rm -rf node_modules/ package-lock.json
      - npm install --omit=dev
artifacts:
  files:
    - "**/*"
